### ISSUE TITLE
ERRNO 103

### ISSUE THREAD

**Issue by MicroPythonUser123** [micropython/micropython-lib#138]
Hello Community!

I have a problem with my ESP8266 module running with micropython 1.8.6.
When i call the client.connect() command i get the following error: 
OSError: [Errno 103] ECONNABORTED
the server runs on my raspberry pi.

Thanks

**Comment by dpgeorge** [comment]
I assume you're trying to use the umqtt module.  By the sounds of your problem it is more of a configuration/usage issue rather than a bug.  Github issues should be used for bugs.  For help using the libraries please ask your question on the forum (in the esp8266 section): http://forum.micropython.org .  Please post there your code and more details about the actual problem.  Thanks!
